### ISSUE TITLE
Test-benches not reporting missing values as errors

### ISSUE THREAD

**Issue by aehart** [cms-L1TK/firmware-hls#125]
All the test-benches should be updated so that missing values are reported as errors. See Robért's report here (slide 4):
https://indico.cern.ch/event/987781/contributions/4171024/attachments/2167770/3659182/20210107_PRMEMC_top_sim.pdf

Those in charge of newly-failing modules (at least the PR and MC) also need to be debugged.

**Comment by bryates** [comment]
@aehart it was a simple change to make the MC throw an error (I just sent truncation=false in the test bench). I pushed this change to the MatchCalculator branch, but I will hold off on a PR until these missing FullMatches are fixed.

**Comment by pwittich** [comment]
@bryates I'm confused by the comments looking at your commit. I think what was requested was to error if there is a mismatch not just in the contents but also in the counts (i.e., throw an error if the emulation predicts N events and the HLS sees N-1.) The code commit message and comments in the code suggest you turned on a Boolean that tells it not to compare the results with the results from emulation that takes into account truncation, which AFAIK is not the same thing?

**Comment by bryates** [comment]
@pwittich the truncation condition was allowing mismatch in the final entries only. By turning it off, the test bench now requires perfect one to one agreement between the test vectors and the firmware output.

Here's an example from the now failing CI:
```
FullMatch:
index	reference	computed
0	0x0c4427604060	0x0c4427604060
1	0x0c8025bfd18b	0x0c8025bfd18b
2	0x0c80a75f51e1	0x0	<=== missing
```
When truncation was set to true, this event would pass. Now it fails, and returns an error.

**Comment by pwittich** [comment]
@meisonlikesicecream @sseifeln @aperloff @djcranshaw and others, can we update the other test benches the same way? 

@bryates should we just create a branch for this explicitly so it can be merged cleanly?

**Comment by sseifeln** [comment]
@pwittich  - I already had the truncation confection  set to false in the IR test bench : 
[https://github.com/cms-tracklet/firmware-hls/blob/IR_Update/TestBenches/InputRouter_test.cpp#L397](url)
but I will move the setting of the condition to the start of the test bench to make it more obvious.

**Comment by meisonlikesicecream** [comment]
The truncation is already set to false in the VMR as well! https://github.com/cms-tracklet/firmware-hls/blob/master/TestBenches/VMRouter_test.cpp#L312

**Comment by pwittich** [comment]
> @pwittich - I already had the truncation condition set to false in the IR test bench :
> [https://github.com/cms-tracklet/firmware-hls/blob/IR_Update/TestBenches/InputRouter_test.cpp#L397](url)
> but I will move the setting of the condition to the start of the test bench to make it more obvious.

great thanks! please push your changes to the branch that Brent made (#126)

**Comment by sseifeln** [comment]
just to check.. the IR in this branch is completely out of date - my fault for the delay in the pull request with the updates to the IR ([https://github.com/cms-tracklet/firmware-hls/pull/113#issuecomment-764668880](url)
Does it still make sense to push my changes to this branch or .. not?

**Comment by pwittich** [comment]
probably we should merge that PR first and then rebase #126 on top of that
