### ISSUE TITLE
During FW sync adjust kMaxProcOffset

### ISSUE THREAD

**Issue by tomalin** [cms-L1TK/firmware-hls#136]
When HLS is next synched to C++, adjust values of kMaxProcOffset in Constants.h. (Should be set to zero for all modules, except for MC, which should be set to 3). -- Numbers from Derek C.

The C++ emulation is given same change via https://github.com/cms-L1TK/cmssw/pull/71 .

This change should not be made now, as the HLS would then be inconsistent with the emData/ files that were generated with the old numbers. It must wait for FW Sync.

**Comment by aehart** [comment]
The HLS has been synced with the current emulation, and `kMaxProcOffset` is now zero for all modules.

@bryates Just to verify, is this correct for the MC? The corresponding offset is 3 in the emulation, but I seem to remember you saying that the structure of the priority encoder in the HLS results in some kind of effective offset.

**Comment by bryates** [comment]
@aehart correct. Until we can emulate the priority encoder, it will need the offset.

**Comment by aehart** [comment]
OK then I think that resolves this issue.
