### ISSUE TITLE
MC missing values

### ISSUE THREAD

**Issue by RobertGlein** [cms-L1TK/firmware-hls#139]
The HLS module has missing values which result in a failure of sim and cosim. These two steps are commented out in order to generate the IP core needed for the PRMEMC chain. Fix these two lines when MC is fixed: https://github.com/cms-L1TK/firmware-hls/blob/HDLTopSim/project/script_MC.tcl#L23-L25

**Comment by aehart** [comment]
Fixed after merge of PR #141.
