### ISSUE TITLE
need to protect printf/cout for inclusion into CMSSW

### ISSUE THREAD

**Issue by pwittich** [cms-L1TK/firmware-hls#152]
Follow what is done for current emulation

**Comment by ryanm124** [comment]
I've mimicked the current emulation's handling of the message logger to update the files in firmware-hls/TrackletAlgorithm. Should the printf/cout in firmware-hls/TestBenches and CMSSW_11_3_0_pre3/src/L1Trigger/TrackFindingTrackletHLS be updated as well?

**Comment by pwittich** [comment]
@ryanm124 I don't think the test benches need to be protected, since they are not used in the CMSSW context, as far as I know. Maybe @skinnari can comment on the second file, or @blwiner or @EmyrClement can answer?

**Comment by ryanm124** [comment]
@pwittich I'm attempting to push my local feature branch so I can merge request and resolve this issue but I'm getting a permission error. Should I switch to a fork of this repository and do my request from there?

**Comment by pwittich** [comment]
> @pwittich I'm attempting to push my local feature branch so I can merge request and resolve this issue but I'm getting a permission error. Should I switch to a fork of this repository and do my request from there?

try again now; I think that I (or whoever added you to the repo) forgot to add you to the hls team.
