### ISSUE TITLE
Use TBHelper in all C++ test benches

### ISSUE THREAD

**Issue by aehart** [cms-L1TK/firmware-hls#176]
Update all C++ test benches for modules included in the summer chain to use the TBHelper class to access test-vector files.

See slides from 18 March for details on the TBHelper class:
https://indico.cern.ch/event/1010698/#3-generalizing-hls-test-benche
Also, see VMRouter_test.cpp, VMRouterCM_test.cpp, and TrackletCalculator_test.cpp for real-life examples of how to use the class.

**Comment by sseifeln** [comment]
Thanks @aehart - I've been in beam test module for 2S+PS modules for the past two weeks and I'm away basically all of this week but I will start when I'm back.
